### PR TITLE
Link to remotestorage.io from docs

### PR DESCRIPTION
**Pull request by jorinvo**
I had the experience of ending up on the doc page while I was actually trying to go to the main website and I couldn't find any link.
Would be good to add some reference. The phrasing can be changed though.

### CODE REVIEW

**Comment by skddc** [comment]
Good idea. Perhaps we should just replace the intro paragraph entirely with the new one from the [README](https://github.com/remotestorage/remotestorage.js/blob/master/README.md)?

**Comment by jorinvo** [comment]
sure, didn't look at the readme. I updated the PR.

**Comment by skddc** [comment]
Cool. Thanks!

**Comment by skddc** [comment]
Dang, just realized that this is RST, not Markdown. Will fix in master.

**Pull request merged**
