### PR TITLE
[WIP] Remove Bluebird dependency

### PR DESCRIPTION
**Pull request by galfert**
connected to #917

* [x] Remove all deprecated `Promise.defer` calls
* [ ] Remove Bluebird
* [ ] Throw error when `Promise` is not defined (telling the developer to include a polyfill)

### CODE REVIEW

**Comment by skddc** [comment]
I'm not sure why we should drop `defer`. It's just a very small wrapper function that I think makes the code easier to read and write: https://github.com/remotestorage/remotestorage.js/blob/master/src/remotestorage.js#L4

At least doesn't really have anything to do with the issue at hand, which is removing Bluebird, not refactoring other code. No?

**Comment by skddc** [comment]
@galfert Any updates/comments here?

**Comment by galfert** [comment]
To be honest I missed @jorinvo's comment and thought we were using the `defer` method that's coming from Bluebird. I only realized this when I actually found the wrapper in `src/remotestorage.js` itself. But at that point I was almost finished with the refactoring.

I'm fine with just closing this whole PR, although I think in some of the cases it still might make sense to use the standard Promise way instead of `defer`.

**Comment by skddc** [comment]
It'd just be easier to remove Bluebird without these changes I think.

**Comment by galfert** [comment]
Fine with me.

**Pull request closed without merging**
