### PR TITLE
Fix case preserving for Dropbox

### PR DESCRIPTION
**Pull request by kevincox**
Untested fix for https://github.com/remotestorage/remotestorage.js/issues/1178

### CODE REVIEW

**Comment by skddc** [comment]
The tasks left that I see:

* Check if all supported APIs/protocols preserve case (especially RS). If not, then preserving case would be incompatible between them, thus impacting data portability.
* Add a test for preserving case specifically

I didn't find anything about case sensitivity in the RS spec at first glance. Perhaps @michielbdejong or @fkooman have insight on this?

I also didn't find a test for it in the [RS API test suite](https://github.com/remotestorage/api-test-suite/), which means it's probably unspecified and different servers may treat it differently at the moment.

**Comment by skddc** [comment]
@michielbdejong Have you seen the question here by any chance?

**Review by DougReeder — CHANGES_REQUESTED** [review]
This approach will fix #1178, which is severe. There will remain some edge cases which are not handled gracefully. Fully handling case-insensitivity would appear to require changes to the sync engine, which deserve a separate commit.

(These commits should probably be cherry-picked into a new PR.)

**Comment by raucao** [comment]
@DougReeder Is the "changes requested" review status about cherry-picking the commits into a new branch?

**Comment by DougReeder** [comment]
Yes, this just needs to be rebased or cherry-picked into a new branch, and to check that all tests still pass.

**Comment by raucao** [comment]
New PR: #1275

**Pull request closed without merging**
