### PR TITLE
Clarify readme.md with note about "npm tests"

### PR DESCRIPTION
**Pull request by theWebalyst**

### CODE REVIEW

**Comment by galfert** [comment]
Thanks for the PR. The note makes sense to me.

+1

**Comment by skddc** [comment]
Yes, thanks and welcome to the project! :)

+1 but see comments on IRC for merge.

**Comment by galfert** [comment]
Merged manually with d2b91e05bffe23e.

Thanks again.

**Comment by skddc** [comment]
@theWebalyst Just FYI: apparently you're using an email that GitHub doesn't know about for your Git commits, so your name isn't linked to your profile in the commit history.

**Comment by theWebalyst** [comment]
@skddc thanks, I've added that email and also switched to using the primary one.

**Pull request closed without merging**
