### PR TITLE
Remove ESLint max-lines limit, update dependencies

### PR DESCRIPTION
**Pull request by skddc**
* Remove max-lines limit
* Update eslint and babel-core
* Fix indentation in CodeClimate config

### CODE REVIEW

**Comment by skddc** [comment]
@galfert Could you run this through your local CodeClimate to see if the `max-lines` error is gone (e.g. sync.js)?

**Comment by galfert** [comment]
No, the error was still there. I noticed that it's not labeled with `[eslint]`, but with `[structure]`.
Took a while to find it in the documentation, but I found the name of the check and disabled it in the Codeclimate config.

**Comment by skddc** [comment]
Oh, ok. Thanks!

**Comment by skddc** [comment]
Rebase and merged locally.

**Pull request closed without merging**
