### PR TITLE
Fix node build, configure browser build

### PR DESCRIPTION
**Pull request by skddc**
This seems to both fix rs.js when used with node.js, as well as still work with at least Browserify (tested with ember-browserify in Webmarks).

refs #1034
connected to #1034

### CODE REVIEW

**Comment by skddc** [comment]
Here's a simple gist of what I used to make sure that the library loads correctly with node.js:

https://gist.github.com/skddc/9f3f5fc0c21b9d92db0d2bffad9a4c29

**Comment by skddc** [comment]
I was playing around a bit more, and pushed the code I created: https://github.com/skddc/rsjs-fun

So, with Webpack it's obviously possible to just pack the whole thing from the node entry point, and because it doesn't export the `xhr2` module, but only sets it on the `global` for the duration of the node program execution, there's also no additional (node-specific) code in the resulting build.

The only potential downside I can see is that people don't add all the polyfills for things we might want to use in the source code, but that would be problematic or just a nuisance.

**Comment by skddc** [comment]
This is ready to be considered for merge.

**Comment by gregkare** [comment]
This works! I tested it on a hubot with the latest hubot-remotestorage-logger with the `global.XMLHttpRequest = require('xhr2');` line removed from `index.js` since it's done by in `node-main.js`

**Comment by gregkare** [comment]
I have also tested it with plain Browserify

**Comment by skddc** [comment]
We'll need some +1s for this to be merged.

**Comment by gregkare** [comment]
I found the original commit adding the `WireClient.readBinaryData` fix: https://github.com/remotestorage/remotestorage.js/commit/5cc64669bff9b4324b74801ce3a68dffa1cf9039, it doesn't contain details though

**Comment by skddc** [comment]
It will still need to overwrite this, if we're unable to detect browser environments here:

https://github.com/remotestorage/remotestorage.js/blob/master/src/wireclient.js#L100-L122

I'd rather detect the environment tbh.

**Comment by galfert** [comment]
> Also, anyone knows what that WireClient.readBinaryData fix is about?

I can't remember exactly anymore, but I think it was to support older Browsers (e.g. Android).

**Comment by skddc** [comment]
@galfert The fix for node is only to remove *all* browser-specific binary file handling. If you look at it, you'll see that it just pipes the `content` argument through to the callback without doing anything.

**Comment by galfert** [comment]
Yes, I was talking about the function itself. In node the whole function isn't needed, so the "fix" just replaces it with a no-op function.

**Comment by galfert** [comment]
Also still works fine when using no module system at all.

+1

**Comment by skddc** [comment]
@galfert You merged this, but the binary data function would certainly fail in node.js now, no?

**Comment by galfert** [comment]
> You merged this, but the binary data function would certainly fail in node.js now, no? I can't see an issue for that.

Yes, I'm currently working on that. I left the original node issue open, so I didn't think it was necessary to create a new one.

**Comment by skddc** [comment]
Ok, I added a comment in the #1034 and re-assigned it from me to you.

**Pull request merged**
