### PR TITLE
udpated package dependencies, tests passing

### PR DESCRIPTION
**Pull request by silverbucket**
updated `jaribu` to the `2.x` branch, which uses minimized output when tests are passing. Also updated the rest of the dependencies (no breaking changes, all tests passing).

### CODE REVIEW

**Comment by skddc** [comment]
Nice! Looking good.

Only thing is, although it passes, I see a metric ton of red errors for the last suite: http://pastie.org/pastes/10143890/text

I like the new output format a lot.

**Comment by skddc** [comment]
The versioning suite also looks a bit weird:

```
= Versioning Suite - testing how sync deals with revisions and conflicts
+ [Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
+ [Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
+ [Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
[Sync] Error [Error: HTTP response code 500 received.]
+ + + + + + +
```

Not sure what 500s have to do with conflicts.

**Comment by silverbucket** [comment]
Yeah I've noticed these in the past as well. So it's not something that's been introduced in the `jaribu` update (they are just more noticeable now). They don't seem to be failing the tests, but I don't really know what the tests are checking for. I think @michielbdejong wrote them?

**Comment by skddc** [comment]
@silverbucket: Any ideas how to proceed with this?

**Comment by skddc** [comment]
It doesn't look bad enough to not merge. It would be helpful if Jaribu had an option for showing the test descriptions again, though. Merged locally after rebase. Thanks, @silverbucket!

**Pull request closed without merging**
