### PR TITLE
Add page about offering Dropbox and Google Drive as a storage option

### PR DESCRIPTION
**Pull request by gregkare**
Connected to #1003

### CODE REVIEW

**Comment by skddc** [comment]
Great!

I'll just edit a tiny little bit before merge.

**Comment by skddc** [comment]
I edited the document. Could someone with a retine/high-res display take a screenshot of the choose-backend screen of the widget please? That way one doesn't even have to start reading to know exactly what this is about. Thanks.

**Comment by gregkare** [comment]
@skddc Here you go

screenshot-2017-10-26 webmarks 1
And just the widget without the border/shadow:

screenshot-2017-10-26 webmarks

**Comment by gregkare** [comment]
Here's a better one with the same almost white background as Read The Docs:

screenshot-2017-10-26 webmarks 2

**Comment by skddc** [comment]
Looking great in the doc!

**Pull request merged**
