### PR TITLE
Allow to configure network request timeout

### LINKED ISSUE #983: Add config for WireClient.REQUEST_TIMEOUT
Used to be possible to configure by just changing the variable on the class, but with the new layout, we need an API for it. That's also the much cleaner way of doing it anyway.

### PR DESCRIPTION
**Pull request by galfert**
Closes #983

Can be set via `setRequestTimeout` and retrieved via `getRequestTimeout`.

### CODE REVIEW

**Comment by skddc** [comment]
Nice!

Did you try this in Sharesome already?

**Comment by galfert** [comment]
> Did you try this in Sharesome already?

No, so far only in the widget demo.

**Comment by skddc** [comment]
The widget demo doesn't upload or download large files, so that wouldn't really make sure the timeout works, no?

**Comment by galfert** [comment]
Since the actual usage of the timeout didn't change, I just added a `console.log` right before where the setting is used to make sure it's using the correct value.

But I will also try it out with Sharesome.

**Comment by galfert** [comment]
I tried it with Sharesome now. First without configuring it explicitly and uploading a large file I got a timeout. Then I configured the timeout to be 90000ms and the upload worked.

I will create a PR for Sharesome once this is published in a release.

**Comment by skddc** [comment]
Awesome!

LGTM

**Comment by skddc** [comment]
@galfert Could you update the CHANGELOG accordingly?

**Comment by galfert** [comment]
Updated the CHANGELOG in 94dda87.

**Comment by skddc** [comment]
Cool, thx.

**Pull request merged**
