### PR TITLE
don't send change event if body nor contentType changed, fixes 764

### PR DESCRIPTION
**Pull request by untitaker**
Rebase of #766

### CODE REVIEW

**Comment by untitaker** [comment]
Some commits from #766 have been cherry-picked into master, but then (probably accidentally) reverted by https://github.com/remotestorage/remotestorage.js/commit/88b8b45cc69d76de067d6bcb9c45fbe9bdd989ed. Even if the new behavior doesn't make it in, I think the commit restoring those tests should be cherry-picked.

**Comment by untitaker** [comment]
I've moved those parts into a new PR: #891.

**Comment by untitaker** [comment]
#766 is now the same as this.

**Comment by skddc** [comment]
Alright, closed the other one. Thanks.

**Pull request closed without merging**
