### PR TITLE
Don't use IndexedDB on iOS 12 and 13

### PR DESCRIPTION
**Pull request by galfert**
Refs #1168

The regex for the version detection is taken from the [Bowser project](https://github.com/lancedikson/bowser).

### CODE REVIEW

**Comment by skddc** [comment]
Could you explain how this behaves with existing local data?

Especially when having edited something locally, but not being synced with a remote, before opening a new app version that switches from IndexedDB to localStorage. Would the new data and changes survive?

**Comment by galfert** [comment]
If saving the data to IndexedDB actually worked and was not prevented by the bug, I think the data would still be in IndexedDB but not be accessible by the app.

**Comment by skddc** [comment]
If the data isn't accessible by the app anymore, then this is a breaking change and needs to be documented properly, no?

**Comment by skddc** [comment]
FYI: I just published a maintenance release that updates all dependencies and fixes all security alerts, before we potentially publish a major version with this breaking change.

**Comment by skddc** [comment]
@galfert What's the current state on iOS? Is this still a necessary fix, for which we need to release the new major version?

**Comment by galfert** [comment]
It's still not fixed on iOS. The bugs (https://bugs.webkit.org/show_bug.cgi?id=197050#c22 and https://bugs.webkit.org/show_bug.cgi?id=202705) are still open.

**Comment by skddc** [comment]
OK, so how do we proceed then? I think we should not merge this without properly documenting the problem for users who may lose access to their data due to this change. And according to SemVer, this should be a major release also.

**Comment by skddc** [comment]
Just FYI: we'll have to tag a major release soon anyway. So this PR could be part of it.

**Comment by raucao** [comment]
Closing, in favor of @galfert's latest idea, which is to do a quick write check when coming back to the foreground and offer to reload in case it fails.

**Pull request closed without merging**
