### PR TITLE
bug fixed for #846

### PR DESCRIPTION
**Pull request by GitGeminiano**
Bug fixed for this issue, please review
https://github.com/remotestorage/remotestorage.js/issues/846

### CODE REVIEW

**Comment by skddc** [comment]
+1

**Comment by Ragnis** [comment]
+1

**Comment by skddc** [comment]
Thanks for fixing, @GitGeminiano!

**Comment by skddc** [comment]
Merged in https://github.com/remotestorage/remotestorage.js/commit/bd2224cd957cf6da8f6795e87643b5c2360016ca

@GitGeminiano Just a hint: if you add the email address, which you're using with Git, to your GitHub account, it will associate your user account with the commit author info and link it.

**Comment by GitGeminiano** [comment]
@skddc Thanks. I will make those changes.

**Comment by skddc** [comment]
@GitGeminiano Hah, nice: just saw that you joined GitHub *yesterday*.

Welcome!

**Pull request closed without merging**
