### PR TITLE
Fix AMD build

### PR DESCRIPTION
**Pull request by skddc**
See commit messages for details.

Connected to #945 
Connected to #917

### CODE REVIEW

**Comment by untitaker** [comment]
As a JS beginner I'm still confused how to use remoteStorage with npm and webpack.

**Comment by skddc** [comment]
Webpack confuses everybody, no matter their JS skill level. ;)

If you use it from npm, you'd just link the `release/...` build in whatever front-end builder you're using (if you're not using it in node.js that is). Or even just have a task that copies it from there to a local folder at a certain point. We're using `release/stable` as path for stable buids now (instead of a version number/name), so you can more easily upgrade via npm.

**Comment by galfert** [comment]
LGTM. +1

**Comment by untitaker** [comment]
I resorted to copying the resulting `.amd.js` into my repo. I also had to patch the file like this:

```diff
diff --git a/home/untitaker/projects/remotestorage/remotestorage.js/remotestorage.amd.js b/lib/remotestorage.amd.js
index f999fa2..5da0933 100644
--- a/home/untitaker/projects/remotestorage/remotestorage.js/remotestorage.amd.js
+++ b/lib/remotestorage.amd.js
@@ -2131,10 +2131,6 @@ define([], function() {
  *
  */
 
-if (typeof XMLHttpRequest === 'undefined') {
-  XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
-}
-
 (function (undefined) {
 
   // URI to property name map

```

Otherwise webpack would look for a xmlhttprequest dependency.

Just installing from npm wouldn't work because that would pull in a `xmlhttprequest` library that itself requires a `fs` module.

**Comment by galfert** [comment]
What? That is only supposed to load that library in Node.

**Comment by untitaker** [comment]
Yes, and apparently webpack can't understand the conditional and thinks that the sourcecode requires `xmlhttprequest`. Which is why I removed the entire thing.

**Comment by skddc** [comment]
> What? That is only supposed to load that library in Node.

Perhaps we should use https://github.com/remotestorage/remotestorage.js/blob/master/src/env.js#L16-L18 then. But not sure if Webpack knows about `window` there.

**Comment by untitaker** [comment]
This `webpack.config.js` fixed it for me:


    module.exports = {
        externals: [
            {xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}'}
        ]
    };

**Comment by skddc** [comment]
Great!

@untitaker @jorinvo Perhaps you could create a little wiki page about using Webpack and/or update https://github.com/remotestorage/remotestorage.js/blob/master/doc/amd.md?

@jorinvo It seems this PR would be enough then, not withstanding better instructions for new users.

**Comment by skddc** [comment]
@jorinvo Could you please take a minute to confirm this fix? Thanks!

**Comment by jorinvo** [comment]
@skddc I don't actively follow the development of remotestorage and I can't actually test this change, but this looks like the right thing to do. 
Removing bluebird is more a performance question I think.
And having a global plus a module.export version looks right. 
Not sure if there are other missing globals interally. Would need to run it to see if it's working. 
Has been really long ago that I was looking into this.

**Comment by theWebalyst** [comment]
Noob warning... but I believe this now works out of the box.

I merged bugfix/945-amd_build_issues with my SAFEnetwork code, rebuilt remotestorage.amd.js, linked to that from litewrite/lib, then ran ```npm run build``` and litewrite appears to work. I don't know its features, but reckon if it starts and I can create a note we're probably good. I have not tried connecting it to any storage tho, so only a superficial test.

I can do some more tests if you want to give me some pointers as to what might be the best things to do, but this has removed the need for me to hack the remotestorage.amd.js in order to get it to function at all.

Hope that helps a bit!

**Comment by skddc** [comment]
> Would need to run it to see if it's working.
> Has been really long ago that I was looking into this.

I could run this build with Litewrite. So it should be easy for you as well to do the same.

**Comment by skddc** [comment]
> I can do some more tests if you want to give me some pointers as to what might be the best things to do, but this has removed the need for me to hack the remotestorage.amd.js in order to get it to function at all.
> 
> Hope that helps a bit!

Yes, it does! The problems were based on loading the libs, so if it works at all, that's confirming the fix. Thank you.

**Comment by skddc** [comment]
Taking @theWebalyst's report as second +1 and merging. Thanks, everyone!

**Comment by untitaker** [comment]
Here's the usage I had success with using Webpack: https://wiki.remotestorage.io/RemoteStorage.js:Beginners%27_Guide#Get_remoteStorage.js

**Comment by skddc** [comment]
Great, thanks!

**Comment by untitaker** [comment]
That's just what I came up with. Perhaps somebody else has found a simpler way (especially regarding the XmlHttpRequest shim).

**Pull request merged**
