### PR TITLE
Use main repo for bower. Resolves #896.

### LINKED ISSUE #896: Use main repo for Bower
Currently, we're using a seperate repo with just the release files for Bower (and until recently also for npm). As discussed during a recent f2f, we should use this main repo for Bower as well, in order to simplify things for both maintainers and users.

In order to have a stable path to release files when updating versions, I'd propose to remove all the old version dirs in `release/` and just have the latest stable release in `release/stable/`.

### PR DESCRIPTION
**Pull request by gunar**
This implements #896. The old [bower-repo](https://github.com/remotestorage/components-remotestorage) should probably be deleted.

### CODE REVIEW

**Comment by gunar** [comment]
Also, the remotestorage bower package should be [unregistered](http://bower.io/docs/creating-packages/#unregister) and again [registered](http://bower.io/docs/creating-packages/#register) with this git-endpoint.

**Comment by untitaker** [comment]
This makes sense. I wonder why we store all releases in the repo when those could be just checked out through the tag.

**Comment by untitaker** [comment]
Could you take a look at this @skddc ?

**Comment by skddc** [comment]
Already did. Sorry. Just wanted to merge locally so I can improve the commit message a little bit.

**Comment by skddc** [comment]
Merged. Thanks, @gunar!

**Comment by skddc** [comment]
The package is un/re-registered as well now!

**Pull request closed without merging**
