### PR TITLE
Update Node.js versions in CI

### PR DESCRIPTION
**Pull request by raucao**

### CODE REVIEW

**Comment by raucao** [comment]
Sounds good to me. Want to have go at that?

**Comment by DougReeder** [comment]
The error message is "test failed ReferenceError: FileReader is not defined". IIRC, it has something to do with what APIs are available in which version of Node.

**Comment by raucao** [comment]
@silverbucket See here: https://github.com/remotestorage/remotestorage.js/issues/1300

**Comment by raucao** [comment]
The remaining test failures are not due to the `FileReader` issue. Only the Webfinger tests are failing, while the `WireClient` ones are passing. PR with actual issue description incoming...

**Pull request closed without merging**
