### PR TITLE
don't send change event if body nor contentType changed

### LINKED ISSUE #764: window-origin change events emitted even if nothing changed
We [try](https://github.com/remotestorage/remotestorage.js/blob/master/src/cachinglayer.js#L323) to not send a window-origin event when changing a document to the same body + content-type, but this is failing because existingNodes has a push version.

Instead of comparing the whole node with the whole existing node, we should compare just their latest versions (common or local)

### PR DESCRIPTION
**Pull request by michielbdejong**
fixes #764

* [x] fix for string data
* [x] write test for this with string data
* [x] fix for binary data
* [x] write test for this with binary data

### CODE REVIEW

**Comment by skddc** [comment]
Still working on this one?

**Comment by skddc** [comment]
^^

**Comment by skddc** [comment]
Bump. /cc @michielbdejong

**Comment by michielbdejong** [comment]
No, I'm no longer working on this, sorry. It would have to be rebased anyway, since the code in master will have changed since september. Maybe the issue addressed by this PR was even fixed since then, and we can close this altogether.

**Comment by skddc** [comment]
Closing in favor of #890.

**Comment by untitaker** [comment]
nonono, the other way around :laugh:

**Comment by skddc** [comment]
Haha, sorry! :blush:

**Comment by galfert** [comment]
I just rebased this PR on the current master and added a test for this.

Currently trying to find out what needs to be done for the binary data fix.

**Comment by skddc** [comment]
w00t!

**Comment by galfert** [comment]
Fixed for binary data as well.

This is all good to go and ready for review now.

**Comment by skddc** [comment]
LGTM and works as intended. Didn't try binary, though.

@galfert Perhaps you can recommend an easy way to manually test that? How did you do it?

**Comment by galfert** [comment]
I adapted a version of sharesome for testing binary. I can publish/deploy that for others to test it as well.

**Comment by skddc** [comment]
Hehe, could've thought of my own app for testing before being pointed to it. :)

If you just push a branch, that'd be dandy.

**Comment by galfert** [comment]
The branch is at https://github.com/galfert/sharesome/tree/test_rs_pr_766

**Comment by skddc** [comment]
Great, thanks.

I just tried and it works just as it should. Except it's loggin to the console without using the rs.js log method/levels. However, I can't see that line in the PR here, so I assume you added it only to that build to be certain, right?

**Comment by galfert** [comment]
> However, I can't see that line in the PR here, so I assume you added it only to that build to be certain, right?

Yes, it's only in the this build for testing this but not the PR.

**Comment by skddc** [comment]
Cool. +1

**Comment by gregkare** [comment]
I have reviewed the code & built this one and used it on https://github.com/galfert/sharesome/tree/test_rs_pr_766 for binary files and on My Favorite Drinks for text

+1

**Pull request merged**
